tokenserver/scripts/process_account_deletions.py

- nothing happens with this extra message read
- causes SQS to timeout on visibility and put it back on the queue
- causes hundreds of messages to pile up waiting for timeout on the
queue

Remove extra SQS message read

---

tokenserver/__init__.py
tokenserver/util.py
tokenserver/views.py

This change adds `fxa_uid` and `device_id` to the generated token as well as logging them for metrics.
For `device_id` it relies on the new `fxa-deviceId` claim from FxA coming in v1.57. When not present it will be a hash of `fxa_uid + 'none'`.

add fxa uid and device_id to tokens

---

circle.yml

- this implements the version object part of the [Dockerflow](https://github.com/mozilla-services/Dockerflow) spec
- paving the way for verification of the image before deployment

implement version doc as part of Dockerflow spec

---

tokenserver/tests/test_service.py
tokenserver/views.py

First stab at implementing `tokenVerified` field validation for FxA-83, sign-in confirmation.
@rfk r?
/cc @vbudhram @shane-tomlinson

feat(server): reject assertions if fxa-tokenVerified is false

---

tokenserver/assignment/sqlnode/migrations/README

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs links for their .org -> .io migration for hosted projects

---

.dockerignore
Dockerfile

- change base to python:2.7-slim
- remove g++ package and deps when using pip
@rfk r? please

Reduce docker image size from 776.5MB => 283.7MB

---

tokenserver/tests/test_service.py
tokenserver/views.py

Fixes https://github.com/mozilla-services/syncserver/issues/89 for self-hosters; @Natim r?
I'll also update the API docs if/when we merge this.

Return a distinct error when rejecting a new user with otherwise valid credentials

---

requirements.txt
tokenserver/tests/test_local_verifier.py
tokenserver/verifiers.py

One day I want to be able to tear down the hosted verifier at https://verifier.accounts.firefox.com, but to do so, we'll need to migrate all sync self-hosters over to doing local verification by default.  This PR:
* Updates to latest PyBrowserID, which supports the extended "idpClaims" necessary for generation-tracking etc to work
* Adds support for "allowed_issuers" setting to the LocalVerifier class, so that it has the same functionality as the default remote verifier.
* Silences PyBrowserID's warning about changing data formats when using the local verifier, since there's pretty clearly not going to be any more changes to that format.
The result will, hopefully, allow self-hosters such as https://github.com/mozilla-services/syncserver/issues/91 to move over to using local verification …

Update LocalVerifer to work more like the default RemoteVerifier

---

circle.yml

This adds the ability to have docker images based on branches.
r? - @mostlygeek, @rfk

circleci: push docker images for branches matching /^dockerpush.*$/

---

.travis.yml
dev-requirements.txt
loadtest/Makefile
loadtest/README.txt
loadtest/loadtest.py
loadtest/mock-oauth-cfn.yml
requirements.txt
setup.py
tokenserver/__init__.py
tokenserver/tests/assignment/test_sqlnode.py
tokenserver/tests/support.py
tokenserver/tests/test_backend_sql.py
tokenserver/tests/test_local_browserid_verifier.py
tokenserver/tests/test_memorynode.ini
tokenserver/tests/test_oauth_verifier.py
tokenserver/tests/test_remote_browserid_verifier.py
tokenserver/tests/test_service.py
tokenserver/verifiers.py
tokenserver/views.py

Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1455219
The main idea here is to fork the "verifier" logic into two different mechanisms - the current one that accepts BrowserID assertions, and a new one that accepts OAuth tokens.  The actual verification of tokens is handled by [PyFxA](https://github.com/mozilla/PyFxA), this just plumbs it in to tokenserver and smooshes the result into a form that matches the output from BrowserID.

Bug 1455219 - Accept FxA OAuth tokens for authorization.

---

requirements.txt
setup.py

There has been a dependency to `umemcache` for many years.
Unfortunately the package is unmaintained since a few years and only supports Python 2. This is one blocker in the move to support Python 3.
Most interestingly there isn't any reference to `umemcache` in the code.
I did some digging on this and it looks like with commit `31eaa57797283b5cd4da5a93450638be9059d1dc` is responsible for removing the component that actually used `umemcache` (_powerhose_), but `umemcache` wasn't touched during this.
The commit mentions [bugzilla #1004246](https://bugzilla.mozilla.org/show_bug.cgi?id=1004246).

Remove the unused umemcache dependency.

---

tokenserver/assignment/sqlnode/sql.py
tokenserver/scripts/purge_old_records.py
tokenserver/tests/test_purge_old_records.py
tokenserver/tests/test_service.py
tokenserver/views.py

This is a sketch of how we might implement #121, sending the raw FxA uid and key-id as part of the hawk token id.   It will need some tests, and it may be an opportunity to refactor out some common helper functions for this stuff.
Connects to #121
/cc @bbangert @philbooth @pjenvey

Include raw FxA user-id and key-id in Hawk token.

---

docker-entrypoint.sh

Small typo, looks like. SERER not SERVER.
r? - @autrilla

fix apparent typo in docker-entrypoint.sh

---

docker-entrypoint.sh

The worker tasks start with a python command line like "python -m tokenserver.scripts.process_account_events -v ./settings.ini ts-account-change-stage". So `docker-entrypoint.sh` needs a case to handle and exec that command.
(Something about this doesn't reallly feel right, though).

provide `python` target on entrypoint for workers

---

tokenserver/assignment/sqlnode/sql.py
tokenserver/scripts/purge_old_records.py
tokenserver/tests/test_purge_old_records.py
tokenserver/tests/test_service.py
tokenserver/views.py

This fixes 2 out of 4 causes of annoying log messages in stage tokenserver loadtests that were reported in [Bug 1533257](https://bugzilla.mozilla.org/show_bug.cgi?id=1533257):
* When the oauth server returns `errno=108`, that just means that the OAuth token has expired. We don't need to log a full traceback in this case.
* When purging old records, don't try to delete from the node if we know it's down.
The other 2 causes will have to be fixed elsewhere.

Reduce annoying log messages in stage loadtests

---

loadtest/mock-oauth-cfn.yml

Ref https://bugzilla.mozilla.org/show_bug.cgi?id=1553020
Mocking `oauth.default_issuer` means that live users can't authenticate
properly via OAuth, because we'll treat them as "uid@mock-issuer" rather
than "uid@live-issuer", preventing them from accessing their sync data.
Instead, ensure that all mock OAuth tokens are explicitly marked as coming
from the mock issuer, and let the default issuer be read from live config
on the target OAuth server.

Bug 1553020 - Don't mock `oauth.default_issuer` for loadtests.

---

README.md
tokenserver/__init__.py

This replaces the current (extremely out-of-date) readme with a description of what the service currently does in practice. It's preparatory work to make it easier to check that we're doing the right thing in https://github.com/mozilla-services/tokenserver/issues/124.
Here is a link to the [rendered markdown doc](https://github.com/mozilla-services/tokenserver/blob/readme-update/README.md).

Update the README to describe current reality of the tokenserver.

---

README.md
tokenserver/tests/test_service.py
tokenserver/views.py

For OAuth clients, the timestamp component of the `X-KeyID` header is supposed to represent the time at which the keys were last changed.  We have instead been using is the "generation number", which is the timestamp at which the user's *password* was last changed.  Once FxA starts [separately tracking the key-rotation timestamp](https://github.com/mozilla/fxa/pull/2570), these two numbers will sometimes diverge and we risk locking out OAuth clients if we continue to use it as the generation number.
This change exempts OAuth clients from the generation-number checking logic, by having them always report a generation number of `0`.

Allow OAuth clients to not report a generation number.

---

setup.py

A new release to get the [oauth generation-number change](https://github.com/mozilla/fxa/pull/2570) out, which is step (1) of (3) in our effort to [track key-rotation timestamps](https://github.com/mozilla-services/tokenserver/issues/124).

Prep v1.4.3

---

Makefile
README.md
tokenserver/assignment/__init__.py
tokenserver/assignment/memorynode.py
tokenserver/assignment/sqlnode/migrations/versions/75e8ca84b0bc_add_keys_changed_at_column.py
tokenserver/assignment/sqlnode/schemas.py
tokenserver/assignment/sqlnode/sql.py
tokenserver/scripts/purge_old_records.py
tokenserver/tests/test_purge_old_records.py
tokenserver/tests/test_service.py
tokenserver/util.py
tokenserver/views.py

This is a quick sketch of the changes that might be required for https://github.com/mozilla-services/tokenserver/issues/124.  It's missing the underlying database migration and any tests, but I wanted to put it up as a kind of explainer for what might be required, and for early feedback.

Track key-rotation timestamp if provided by the IdP

---

setup.py

We ain't exactly semver in here, but since this includes the significant new feature of [tracking keys_changed_at timestamps](https://github.com/mozilla-services/tokenserver/issues/124), it seemed appropriate to rev the minor version number.

Prep v1.5.0

---

tokenserver/assignment/sqlnode/schemas.py

Commit 71a590f85a27eff6ee4cddfe25aaeb33d210baa2 appears to have introduced a subtle difference between the schema declared in `schemas.py` and the one that would be produced by running all our migrations in order.  It added a migration making `nodeid` non-nullable and adding an index on `nodeid`, but updated the schema to make `nodeid` nullable and add an index on the
pair (`service`, `nodeid`).
This commit fixes the schema to match what's in the database in production. For good measure I have also re-ordered the columns to match the order they physically appear in the database in production.  With this change, a db re-created from scratch using the declarations in `schemas.py` should end up being the same shape as in prod.

Adjust schemas.py to reflect state of DB after migration scripts.

---

README.md
etc/tokenserver-dev.ini

This instructions didn't work, so I fixed 'em up so they do.

Update README so "how to run the server" actually works.

---

tokenserver/assignment/sqlnode/sql.py
tokenserver/tests/test_backend_sql.py
tokenserver/tests/test_process_account_events.py
tokenserver/tests/test_purge_old_records.py
tokenserver/tests/test_service.py
tokenserver/tests/test_sql.ini

In the SQL backend, when updating a user's details, we try to do an in-place update rather than a replacement when the generation number is the only field that has changed.
Due to a bug, this branch was being taken even if the `keys_changed_at` field has changed, with the result being that the new `keys_changed_at` value just gets dropped on the floor.  This showed up in QA of the v1.5.0 release, when I tried to test against a user that already exists in the db.
The first commit here fixes the above bug, and is pretty trivial.
Unfortunately, I wasn't able to reproduce the bug in tests here, because most of the service API tests are only run against the memory backend, which didn't have the bug! I've therefore added a second commit here, which tries to ensure that these also get run …

Correctly write keys_changed_at when it's the only updated field.

---

tokenserver/__init__.py
tokenserver/tests/test_memorynode.ini
tokenserver/tests/test_node_type_classifier.py
tokenserver/tests/test_service.py
tokenserver/tests/test_sql.ini
tokenserver/views.py

Ref [Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1582317](https://bugzilla.mozilla.org/show_bug.cgi?id=1582317); obviously extremely WIP!
The idea here is to have tokenserver return a short string value for clients to include in the sync ping, which we can use for segmented analysis of sync client metrics. By putting the server in charge of this value we gain a lot of operational flexibility without having to update client code - for example, if the initial rollout of a `"new`" node type is a bit of a bust, we might like to be able to introduce a `"new2"` node type without disrupting the users already allocated to the previous one.
There are many wayswe could have tokenserver determine the appropriate value to send - we could make it a column in the `nodes` table, we could do a …

Report `node_type` for inclusion in client-side metrics.

---

setup.py
tokenserver/assignment/memorynode.py
tokenserver/assignment/sqlnode/sql.py
tokenserver/tests/test_service.py

During the initial rollout of keys_changed_at, we may be in a situation where the tokenserver first sees a new value for keys_changed_at after some older version of the server has already processed the node-reassignment for the corresponding change in client_state. We don't want to force users through
another node-reassignment in that case, since they would already have done one.
This changes the sql backend to only force a node-reassignment when client_state changes, and adds some tests to ensure it. The memory backend was accidentally doing the right thing already, although the tests uncovered an issue with handing out mutable references to its internal state that I've had to fix as part of this PR.

Don't force a node-reassigment when recording a new value of keys_changed_at

---

tokenserver/assignment/sqlnode/sql.py
tokenserver/scripts/purge_old_records.py
tokenserver/tests/assignment/test_sqlnode.py

r? - @rfk
I was working with the purge task in production to get it to run more effectively, and noticed a couple of things.
1. the default max-per-loop of 10 meant that each task was spending a large chunk of each cycle doing the select, and spinning a lot of database cpu. So I'll be using a max-per-loop of ~1000 going forward.
2. Due to the current select for old_records, each purge task winds up working on the same set of old_records. So this PR adds a --max-offset option to the task. The idea is that if each instance's task picks a random offset < max_offset, then it will be unlikely to have any 2 instances working on the same set of records. I'm thinking of running something like max-per-loop=1000 and max-offset=100000. The offset will add some additional cost to each select, so I'll …

purge_old_records: add --max-offset option and some additional logging statements

---

tokenserver/assignment/sqlnode/migrations/versions/5d056c5b8f57_create_dyn_settings_table.py
tokenserver/assignment/sqlnode/schemas.py
tokenserver/assignment/sqlnode/sql.py
tokenserver/assignment/sqlnode/sqliteschemas.py

Allows ops to modify `dynamic_settings` `migrate_new_user_percentage`
without requiring a redeployment.
Closes #165

feat: add dynamic_settings table for on-the-fly ops config

---

tokenserver/assignment/sqlnode/sql.py
tokenserver/scripts/purge_old_records.py
tokenserver/tests/assignment/test_sqlnode.py

Future me will not remember the details of why downed nodes are excluded from `get_old_user_records`; this renames it to more fully describe what the result should be used for and adds some docs about it. @jrgm r?

Rename `get_old_user_records` to `get_old_user_records_purge`.

---

tokenserver/assignment/sqlnode/sql.py
tokenserver/tests/assignment/test_sqlnode.py

If a user's current storage node is decomissioned, they may end up
without an active `users` record in the db, and there is code to
handle this case by lazily recreating an active record on demand.
Previously, this code would only copy `generation` and `client_state`
fields, essentially forgotten any previously-seen value for the new
`keys_changed_at` field. This commit fixes things so that value is
also remembered.
I do not expect this bug to have caused any issues in practice, since
we already have a bunch of code to handle users for which we have
not yet seen a value of `keys_changed_at`. But we should remember it
when we can because it helps the server enforce that clients are
behaving correctly.

fix: remember keys_changed_at when reallocating after node replacement.

---

tokenserver/tests/test_service.py
tokenserver/views.py

Past-rfkelly helpfully left a `TODO` item in the code for checking consistency of `keys_changed_at`, which I went to revisit in light of [Bug 1613032](https://bugzilla.mozilla.org/show_bug.cgi?id=1613032).
Unfortunately for Past-rfkelly, his reasoning that we could add this check once all servers are running the latest code is not sound. There's a (very very small) chance that a user could have:
* Synced once against a new server, recording a `keys_changed_at` timestamp
* Reset their account password, then synced once against an older server during the rollout of the `keys_changed_at` feature, recording an updated `generation` but leaving the old `keys_changed_at`.
* Never synced again after that.
When this user suddenly comes back and syncs against a server with the proposed additional …

Revisit some TODO items around keys_changed_at consistency checks.

---

.circleci/config.yml
requirements.txt

I noticed this message go by in a failing build:
```
Attempting uninstall: cffi
Found existing installation: cffi 1.13.2
Can't uninstall 'cffi'. No files were found to uninstall.
```
... and so I tried changing that in requirements.txt to match that version, and surprise, it "works".
This PR also includes the circle-ci test from https://github.com/mozilla-services/tokenserver/pull/188 and the `docker run app:build server` shows that it starts up there.
I put this on stage, and the tokenserver daemon starts up and runs. However the event processor job fails with `/usr/bin/python: No module named zope.interface` so more work to do, but I'm going to stop for now.

fix: use cffi 1.13.2 because reasons

---

.circleci/config.yml

Check that the docker image can be used for production.
This PR currently fails due to the CFFI/gunicorn issue, but a passing circleci run can be seen on a branch based on 1.5.5 in https://app.circleci.com/pipelines/github/mozilla-services/tokenserver/31/workflows/aa2aef31-8c37-47c6-961e-fae777be130e/jobs/410
(A further improvement to this test would be to make it connect to a mysql URL, but for now go with a sqlite url).

docker: check that entrypoints and gunicorn work

---

.circleci/config.yml
docker-entrypoint.sh
requirements.txt

Allow `pypy` in docker-entrypoint.sh

fix: allow `pypy` in docker-entrypoint.sh

---

Makefile
requirements.txt

Newer versions of `pip` do not work with `pypy` v2.7 on some platforms, ref https://github.com/pypa/pip/issues/8653

Pin the version of `pip` used in the `pypy` virtualenv.
