mozilla-services/tokenserver

Dockerfile

- Make Dockerfile more cache friendly

Improvements to Tokenserver Dockerfile

---

.travis.yml
Dockerfile

Changes
- run tokenserver as a non-privileged user `app` in the container 
- update the .travis.yml to automatically build, test and push docker containers to dockerhub using the new cloudops dockerflow.

Docker flow improvements

---

.travis.yml
README.md
circle.yml

- Returned travis-ci to its original configuration 
- Implemented circle-ci to build containers
@rfk please r?

Refactor CI and Docker container building

---

tokenserver/scripts/process_account_deletions.py

Handle `reset` events from the auth-server by updating the user's `generation`.

add fxa account reset event processing

---

tokenserver/scripts/process_account_events.py

@mostlygeek you brought it up, you get to review it ;-)
This also adds a warning log on unrecognized event types, but still deletes them from the queue as we're not sending any messages that we can't afford to lose, and this way we don't have to worry about a backlog.

Rename process_account_deletions script to reflect more generic nature.

---

circle.yml

@rfk r? 
This fixes circleCI builds failing due to PRs from forks

fixes #82 circleci PR builds

---

circle.yml

Fixes broken deployment of `:latest` container to dockerhub when merges go into master

fix broken deployment of :latest to dockerhub

---

tokenserver/assignment/sqlnode/sql.py
tokenserver/scripts/process_account_events.py
tokenserver/tests/test_process_account_events.py

Check exitence of user record when processing account reset event.

---

tokenserver/tests/test_service.py
tokenserver/views.py

Fixes #92; @mhammond @dannycoates r?

Return hashed fxa uid

---

.travis.yml
Makefile
circle.yml
dev-requirements.txt
setup.py
tokenserver/tests/assignment/test_sqlnode.py
tokenserver/tests/support.py
tokenserver/tests/test_backend_sql.py
tokenserver/tests/test_memorynode.py
tokenserver/tests/test_process_account_events.py
tokenserver/tests/test_purge_old_records.py
tokenserver/tests/test_remote_verifier.py
tokenserver/tests/test_service.py
tokenserver/views.py

Based on #99
r? @mozilla-services/verbatim-project

Upgrade to cornice 2 and drop support for Python 2.6

---

setup.py

Release v1.2.24 to include changes from PR #98, #99 and #100 (when they all land)

Prep v1.2.24

---

.travis.yml
Makefile
tokenserver/tests/test_service.py
tokenserver/views.py

Fixes #113; @vladikoff could you pls give me a quick sanity-check r? here?

Fix validation of X-Client-State header.

---

tokenserver/scripts/process_account_events.py
tokenserver/tests/test_process_account_events.py

This will help to more quickly lock out disconnected devices when the user changes their account password, as described in [Bug 1457851 Comment 7](https://bugzilla.mozilla.org/show_bug.cgi?id=1457851#c7).  @jrconlin are you up for another, hopefully simpler r? here?

Bug 1457851 - Add back-channel generation update on password change.

---

requirements.txt

Resolves a security warning; @mozilla-services/sync-devs r?

Bump urllib3 dependency.

---

setup.py

Making a new release to include the raw-FxA-uid stuff needed for spanner.

Prep v1.4.0

---

docker-entrypoint.sh

Per https://bugzilla.mozilla.org/show_bug.cgi?id=1528821#c13; @jrgm r?

Bug 1528821 Comment 13: restore previous gunicorn worker settings

---

setup.py

I've already pushed the tag, but here's the commit for merge to master.

Prep v1.4.1

---

setup.py

Already tagged, r? for merge to master.

Prep v1.4.2

---

setup.py

Redo of 1.4.3:
https://github.com/mozilla-services/tokenserver/pull/145#issue-329552305

Prep v1.4.4

---

requirements.txt

targeted to master and signed now.

update requests for urllib3 version disagreement

---

setup.py

Tagged already, this is for merge to master.

Prep v1.4.5

---

tokenserver/tests/test_service.py

This is a quick followup to https://github.com/mozilla-services/tokenserver/pull/183 which I thought I'd add for completeness. Since it passes AFAICT, there's no need to get this in to the upcoming release, I tried it out locally anyway so might as well include it for future use.

Test that generation numbers provided by OAuth are correctly handled by the service.

---

requirements.txt
tokenserver/tests/test_sql.ini

bug: revert PyFxA due to possible spike in performance

---

setup.py

* revert PyFxA due to possible spike in performance (2ba62ff1ee60b7629066330b1a817b3250ef72e8)

chore: tag 1.5.7

---

setup.py

*   switch to pypy ([22b99ac9](22b99ac9))
*   add dynamic_settings table for on-the-fly ops config ([e25d6367](e25d6367), closes [#165](165))
*   Add percentage routing and migration status to user table ([050ab537](050ab537), closes [#159](159))
* **server:**  reject assertions if fxa-tokenVerified is false ([e1c6f2a3](e1c6f2a3))
*   only install cffi for CPython ([6f5d2e7e](6f5d2e7e))
*   allow `pypy` in docker-entrypoint.sh ([757cce90](757cce90))
*   use cffi 1.13.2 because reasons ([c283e4fc](c283e4fc))
*   remember keys_changed_at when reallocating after node replacement. ([ee6c065d](ee6c065d))
* **deps:**  Update SQLAlchemy to latest version ([eb2256f6](eb2256f6))

chore: tag 1.5.8

---

setup.py

chore: tag 1.5.9

---

requirements.txt
tokenserver/assignment/sqlnode/migrations/env.py
tokenserver/tests/test_sql.ini
tokenserver/verifiers.py

It looks like FxA might want JSON strings in it's Client.__init__() but
later use JSON objects. This is a bit of a monkeypatch to work around
that bug for now.

f work around possible bug in fxa

---

Makefile

e.g. make -e PTYPE=python
Closes #210

feat: allow specifying the python interpreter

---

dev-requirements.txt
tokenserver/scripts/purge_old_records.py
tokenserver/tests/assignment/test_sqlnode.py
tokenserver/tests/test_oauth_verifier.py
tokenserver/tests/test_purge_old_records.py
tokenserver/verifiers.py

add `dryrun` and `max-records` to purge_old_records script

feat: add dryrun and limit to purge_old_records.py script
